import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { getGroceryList, getStoreLinks, getTodayMealPlan } from '../api/apiClient';

export default function GroceryListPage() {
  const navigate = useNavigate(); const username = sessionStorage.getItem('nourishpath_demo_user');
  const [groups, setGroups] = useState([]); const [links, setLinks] = useState({}); const [error, setError] = useState('');
  useEffect(() => { if (!username) { navigate('/'); return; } getTodayMealPlan(username).then(({ plan }) => getGroceryList(username, plan._id)).then(({ groceryList }) => setGroups(groceryList)).catch((requestError) => setError(requestError.message)); }, [navigate, username]);
  async function showStores(item) { try { const result = await getStoreLinks(item); setLinks((current) => ({ ...current, [item]: result.links })); } catch (requestError) { setError(requestError.message); } }
  return <main className="min-h-screen bg-leaf-50 px-5 py-8 text-slate-900"><section className="mx-auto max-w-4xl"><Link className="text-sm font-medium text-leaf-700" to="/meal-plan">← Today’s meal plan</Link><h1 className="mt-5 text-3xl font-bold">Your grocery list</h1><p className="mt-2 text-slate-600">Suggested quantities for today’s meals. Store links open a search page; NourishPath does not process payments.</p>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<div className="mt-6 space-y-5">{groups.map((group) => <section className="rounded-2xl bg-white p-6 shadow-sm" key={group.category}><h2 className="text-xl font-bold">{group.category}</h2><div className="mt-4 divide-y divide-slate-100">{group.items.map(({ item, quantity }) => <div className="py-4" key={item}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium capitalize">{item}</p><p className="text-sm text-slate-500">{quantity}</p></div><button className="rounded-lg border border-leaf-700 px-3 py-2 text-sm font-semibold text-leaf-700" onClick={() => showStores(item)}>Find in stores</button></div>{links[item] && <div className="mt-3 flex flex-wrap gap-2">{Object.entries(links[item]).map(([store, url]) => <a className="rounded-lg bg-leaf-50 px-3 py-2 text-sm font-medium text-leaf-700" href={url} key={store} rel="noreferrer" target="_blank">{store}</a>)}</div>}</div>)}</div></section>)}</div></section></main>;
}
