import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { generateMealPlan, getTodayMealPlan } from '../api/apiClient';

export default function MealPlanPage() {
  const navigate = useNavigate(); const username = sessionStorage.getItem('nourishpath_demo_user');
  const [plan, setPlan] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  async function loadPlan(generate = false) { setLoading(true); setError(''); try { const result = generate ? await generateMealPlan(username) : await getTodayMealPlan(username); setPlan(result.plan); } catch (requestError) { if (!generate && requestError.message.includes('No meal plan')) return loadPlan(true); setError(requestError.message); } finally { setLoading(false); } }
  useEffect(() => { if (!username) { navigate('/'); return; } loadPlan(); }, [username]);
  if (loading) return <main className="grid min-h-screen place-items-center bg-leaf-50 text-leaf-700">Creating your balanced meal plan…</main>;
  return <main className="min-h-screen bg-leaf-50 px-5 py-8 text-slate-900"><section className="mx-auto max-w-5xl"><Link className="text-sm font-medium text-leaf-700" to="/profile">← Edit profile</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="font-semibold text-leaf-700">Today’s plan</p><h1 className="text-3xl font-bold">Balanced Indian meals</h1></div><button className="rounded-xl bg-leaf-700 px-4 py-3 font-semibold text-white" onClick={() => loadPlan(true)}>Regenerate plan</button></div>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{plan && <><div className="mt-6 grid gap-4 sm:grid-cols-3">{[['Calories', plan.dailyNutritionTotals.calories], ['Protein', `${plan.dailyNutritionTotals.protein} g`], ['Fibre', `${plan.dailyNutritionTotals.fiber} g`]].map(([label, value]) => <div className="rounded-2xl bg-white p-5 shadow-sm" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</div><div className="mt-6 grid gap-5 md:grid-cols-2">{plan.meals.map((meal) => <article className="rounded-2xl bg-white p-6 shadow-sm" key={meal.mealType}><p className="text-sm font-semibold uppercase tracking-wider text-leaf-700">{meal.mealType}</p><h2 className="mt-1 text-xl font-bold">{meal.name}</h2><p className="mt-2 text-slate-600">{meal.description}</p><p className="mt-4 text-sm text-slate-500">{meal.nutrition.calories} kcal · {meal.nutrition.protein} g protein · {meal.nutrition.fiber} g fibre</p><p className="mt-3 text-sm text-slate-500">Ingredients: {meal.ingredients.join(', ')}</p></article>)}</div><p className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950">{plan.disclaimer}</p></>}</section></main>;
}
