import { useState } from 'react';
import { Link } from 'react-router-dom';
import { generateWeeklyPlan } from '../api/apiClient';

export default function WeeklyPlanPage() {
  const username = sessionStorage.getItem('nourishpath_demo_user'); const [plans, setPlans] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function generate() { setLoading(true); setError(''); try { const result = await generateWeeklyPlan(username, new Date().toISOString().slice(0, 10)); setPlans(result.plans); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-leaf-50 px-5 py-8 text-slate-900"><section className="mx-auto max-w-5xl"><Link className="text-sm font-medium text-leaf-700" to="/meal-plan">← Today’s meal plan</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="font-semibold text-leaf-700">Weekly variety</p><h1 className="text-3xl font-bold">Your 7-day meal timeline</h1><p className="mt-2 text-slate-600">Plans use recent meal history to reduce repeated meals and ingredients.</p></div><button className="rounded-xl bg-leaf-700 px-4 py-3 font-semibold text-white disabled:opacity-60" disabled={loading} onClick={generate}>{loading ? 'Generating 7 days…' : 'Generate 7-day plan'}</button></div>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<div className="mt-6 grid gap-4 md:grid-cols-2">{plans.map((plan) => <article className="rounded-2xl bg-white p-6 shadow-sm" key={plan._id}><div className="flex justify-between gap-3"><h2 className="font-bold">{plan.planDate}</h2><span className="rounded-full bg-leaf-50 px-3 py-1 text-sm font-semibold text-leaf-700">Variety {plan.variationScore}%</span></div><ul className="mt-4 space-y-2 text-sm text-slate-700">{plan.meals.map((meal) => <li key={meal.mealType}><span className="font-semibold capitalize">{meal.mealType}:</span> {meal.name}</li>)}</ul>{plan.repeatedIngredients.length > 0 && <p className="mt-4 text-xs text-slate-500">Repeated staples: {plan.repeatedIngredients.join(', ')}</p>}</article>)}</div>{!plans.length && !loading && <p className="mt-8 rounded-2xl border border-dashed border-leaf-700/30 p-6 text-slate-600">Generate a timeline when you are ready. It makes up to seven AI requests.</p>}</section></main>;
}
